name: date_picker_custom
description: A custom date_picker component copy from Flutter Material
version: 0.0.1
homepage: https://github.com/diegosk87/date_picker_custom

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter: